### ISSUE TITLE
Error after upgrading to 1.0.5 and higher

### ISSUE THREAD

**Issue by macav** [infinitered/apisauce#234]
After upgrading from 1.0.3 to 1.0.5 and higher, I'm getting this error in Jest:
`/Users/macav/Projects/p/app/node_modules/axios/lib/adapters/http.js:237
          require('./../core/settle')(resolve, reject, response);`
..
`require is not a function`

Seems to be related to axios upgrade to 0.19.0, but I didn't find any information there either. Any idea what could be wrong?

**Comment by robinheinze** [comment]
Hey @macav, sorry for the delay. Are you still having this issue? If so are you able to workaround by downgrading to 1.0.3?

**Comment by macav** [comment]
Hi @robinheinze , thanks for the reply! Yes, we have it now fixed to 1.0.3 and it works fine. I cannot go higher. The issue is still present in 1.1.1.

**Comment by chakrihacker** [comment]
Is this issue still persists or can this be closed?

**Comment by absmugz** [comment]
there has not been a response, closing this
